### ISSUE TITLE
Compilation on Arch Linux very slow

### ISSUE THREAD

**Issue by ronaldtse** [fontist/extract_ttc#9] opened 2022-09-19 07:09 UTC
When installing this gem on Arch Linux, the compilation goes really slow:

```
$ docker run --platform linux/amd64 -it archlinux bash
## (in docker container)
$ pacman -Sy
$ yes | pacman -Sy git ruby jre-openjdk-headless gcc libffi libxml2 libxslt make
$ gem install extract_ttc
...
Successfully installed extract_ttc-0.1.0
Building native extensions. This could take a while...
... (very slow)
```

**Comment by ronaldtse** [comment] 2022-09-19 08:48
I wonder if this is due to the compilation of libffi or extract_ttc...

**Comment by CAMOBAP** [comment] 2023-03-26 20:59
Hmm, cannot reproduce it with the steps above. Prebuilt was installed for `extract_ttc` i.e. `extract_ttc-0.3.5-x86_64-linux.gem`

It can be related to `ffi` but in my case it was compiled fast also

Also according to the log it was collected for `0.1.0` for that version there was no prebuilt version https://rubygems.org/gems/extract_ttc/versions/0.1.0

So I',m going to close this as outdated, feel free to reopen it

**Closed by CAMOBAP** 2023-03-26 20:59 UTC
Labels: help wanted
